### ISSUE TITLE
実装項目の順序の決定・洗い出し

### ISSUE THREAD

**Issue by Crea7dosSantos** [kok1219/HitAndBlow#8]
1. 重複のない4桁のランダムな数字を作成 #1 
2. 4桁の数字と入力した数字の判定 #3 
3. 正解まで繰り返し判定を繰り返す #4 
4. 正解までの回数を記録 #5 
5. クリアボタンを押すと最初からゲームをスタート #6

**Comment by Crea7dosSantos** [comment]
@kok1219 正解までの繰り返し判定って何を想定してる？

**Comment by kok1219** [comment]
4桁の数字と入力した数字が合うまで、入力繰り返す！
見返したら意味不明な日本語だった

**Comment by Crea7dosSantos** [comment]
@kok1219 
あんまりぴんとこないな〜
俺だったら
1. 0~9で重複のない4桁の乱数を作成
2. 入力された4桁が数字かどうかの判定
3. 入力された4桁の数字に0~9の範囲で重複がないかの判定
4. 入力値に問題があった場合は、問題を出力しその後の処理はスキップ
5. 成功までの回数をカウントアップ
6. 4桁の乱数と4桁の入力された数字の比較
7. 比較結果の出力
8. 挑戦成功時には挑戦回数を出力
9. 挑戦成功時にクリアボタンを表示し、ボタンが押されたら再スタート

かな。あくまでも繰り返すのは入力次第だからプログラムとして考慮する必要はないんじゃない？
挑戦成功時のみクリアボタンを表示するフローに入るのだから、挑戦失敗時の挑戦結果を出力した後は特に繰り返しなどのプログラムを書く必要はないよね

**Comment by kok1219** [comment]
＞挑戦成功時のみクリアボタンを表示するフローに入るのだから、挑戦失敗時の挑戦結果を出力した後は特に繰り返しなどのプログラムを書く必要はないよね
→わかってないかも、、

**Comment by kok1219** [comment]
あ、理解した！

**Comment by kok1219** [comment]
ゆーさくのイシュー通りにやってみる！
